version: '3'
services:
  restaurant-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["sh", "-c", "npm run console:dev import-restaurants && npm run start:dev"]
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
